version: '3'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: certificat_generator_react
      DB_USERNAME: root
      DB_PASSWORD: ''
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: certificat_generator_react
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"

  vite-react-app:
    build:
        context: .
        dockerfile: react-certificate/Dockerfile
    ports:
        - "80:80"
